nvimTree = require('tree')
neogit = require('neogit')
require('lsp')
require('statusline')
require('treesitter')
require('whichkey')
require('colorizer').setup()
require('neoscroll').setup()
require('nvim-autopairs').setup()
